version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: tonio
      RABBITMQ_DEFAULT_PASS: tonio
